default: &default
  host: <%= ENV.fetch('APP_HOST', 'localhost') %>
  port: <%= ENV.fetch('APP_PORT', '') %>
  protocol: <%= ENV.fetch('APP_PROTOCOL', 'http') %>
  admin:
    username: <%= ENV.fetch('ADMIN_USERNAME', 'admin') %>
    password: <%= ENV.fetch('ADMIN_PASSWORD', 'admin') %>

development:
  <<: *default

test:
  <<: *default
  admin:
    username: admin
    password: admin

staging:
  <<: *default

production:
  <<: *default
